version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build: ./app
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
